# EXECUTIVE SUMMARY {#sec-executive-summary}

\textit{{Drug X, an oral tablet which is being developed by company A and is used to treat Disease Y, has undergone N number of completed studies. A population PK analysis was performed to characterize the PK and identify sources of variability in the PK  based on rich and sparse samples collected in Phase 1 and Phase 3 studies. As part of the population PK analysis, data from NN subjects was utilized where the doses were ranging from 5 mg- 100 mg Q3W.
The data was adequately described using a 1-compartment model with a first-order absorption rate constant (Ka) with lag time (Tlag). A bootstrap method resulted in model reduction compared to reducing the full model with the additional of all the covariates like (age, sex, baseline body weight, race, baseline GFR, drug product)  by removing covariates for which the 95% PIs included the null value relative to the reference compared stepwise covariate modeling using forward addition and backward elimination. Both continuous and categorical variables were evaluated and. The final population estimates of CL/F and V/F for drug X were 19.49 L/h and 198.72 L, respectively, and are for a male patient who is 92.5 kg, has a CRCL of 116.5 mL/min, and is taking a dose of 150 mg. Based on the population PK model, the half-life of drug X was 7.07 The effect of creatinine clearance was added on CL/F since the drug was previously demonstrated as important  as Drug X is expected to undergo renal excretion. Baseline body weight of each subjects was modeled as covariate on the CL, VC using a power function and the the estimates are  respectively.Sex was a significant covariate on CL and VC (Figure 6), with male subjects having a higher CL and higher Vc than female subjects.
Final Model-based simulations were performed to evaluate drug X CL under various conditions, estimate effective half-life, predict exposure metrics for 60 mg Q4W vs 30 mg Q2W dose regimens, and assess the clinical relevance of covariates of interest such as sex, hepatic function, renal function, race, manufacture process, and shorter infusion time in the final PPK model. Results suggest that exposures were higher in female subjects than males for subjects who received 60 mg Q4W. The predicted geometric means of drug X exposure (Cmin1, Cmax1, Cavg1, Cavd28, Cminss, Cmaxss, and Cavgss) at 60 mg Q4W and 30 mg Q2W are summarized in Table 5.  As expected, Cavgss was similar across the two different regimens (difference < 5%). The exposures were higher with drug X 30 mg Q2W relative to 60 mg Q4W by approximately 51% for Cmind28 and 42% for Cminss. The exposures were lower with drug X 30 mg Q2W relative to 60 mg Q4W by approximately 50% for Cmax1 and 31% for Cmaxss, which were also expected.
}}